/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DeliberaVotingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "castVote"
      | "confidentialProtocolId"
      | "createProposal"
      | "finalize"
      | "getEncryptedApproved"
      | "getEncryptedRejected"
      | "getProposal"
      | "hasVoted"
      | "owner"
      | "proposalCount"
      | "publishResult"
      | "setTeeAddress"
      | "teeAddress"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ProposalCreated"
      | "ProposalFinalized"
      | "ResultPublished"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "castVote",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedRejected",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publishResult",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTeeAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "teeAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "finalize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedRejected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTeeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "teeAddress", data: BytesLike): Result;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    description: string,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    description: string,
    deadline: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    description: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalFinalizedEvent {
  export type InputTuple = [proposalId: BigNumberish];
  export type OutputTuple = [proposalId: bigint];
  export interface OutputObject {
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultPublishedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    approved: BigNumberish,
    rejected: BigNumberish,
    decision: string
  ];
  export type OutputTuple = [
    proposalId: bigint,
    approved: bigint,
    rejected: bigint,
    decision: string
  ];
  export interface OutputObject {
    proposalId: bigint;
    approved: bigint;
    rejected: bigint;
    decision: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [proposalId: BigNumberish, voter: AddressLike];
  export type OutputTuple = [proposalId: bigint, voter: string];
  export interface OutputObject {
    proposalId: bigint;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DeliberaVoting extends BaseContract {
  connect(runner?: ContractRunner | null): DeliberaVoting;
  waitForDeployment(): Promise<this>;

  interface: DeliberaVotingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  castVote: TypedContractMethod<
    [proposalId: BigNumberish, encryptedVote: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createProposal: TypedContractMethod<
    [description: string, duration: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  finalize: TypedContractMethod<
    [proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEncryptedApproved: TypedContractMethod<
    [proposalId: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedRejected: TypedContractMethod<
    [proposalId: BigNumberish],
    [string],
    "view"
  >;

  getProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [
      [string, bigint, bigint, boolean, bigint, bigint] & {
        description: string;
        deadline: bigint;
        voteCount: bigint;
        finalized: boolean;
        resultApproved: bigint;
        resultRejected: bigint;
      }
    ],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [proposalId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  proposalCount: TypedContractMethod<[], [bigint], "view">;

  publishResult: TypedContractMethod<
    [proposalId: BigNumberish, approved: BigNumberish, rejected: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTeeAddress: TypedContractMethod<
    [_teeAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  teeAddress: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "castVote"
  ): TypedContractMethod<
    [proposalId: BigNumberish, encryptedVote: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [description: string, duration: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalize"
  ): TypedContractMethod<[proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncryptedApproved"
  ): TypedContractMethod<[proposalId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedRejected"
  ): TypedContractMethod<[proposalId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [proposalId: BigNumberish],
    [
      [string, bigint, bigint, boolean, bigint, bigint] & {
        description: string;
        deadline: bigint;
        voteCount: bigint;
        finalized: boolean;
        resultApproved: bigint;
        resultRejected: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [proposalId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "publishResult"
  ): TypedContractMethod<
    [proposalId: BigNumberish, approved: BigNumberish, rejected: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTeeAddress"
  ): TypedContractMethod<[_teeAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "teeAddress"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalFinalized"
  ): TypedContractEvent<
    ProposalFinalizedEvent.InputTuple,
    ProposalFinalizedEvent.OutputTuple,
    ProposalFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "ResultPublished"
  ): TypedContractEvent<
    ResultPublishedEvent.InputTuple,
    ResultPublishedEvent.OutputTuple,
    ResultPublishedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "ProposalCreated(uint256,string,uint256)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalFinalized(uint256)": TypedContractEvent<
      ProposalFinalizedEvent.InputTuple,
      ProposalFinalizedEvent.OutputTuple,
      ProposalFinalizedEvent.OutputObject
    >;
    ProposalFinalized: TypedContractEvent<
      ProposalFinalizedEvent.InputTuple,
      ProposalFinalizedEvent.OutputTuple,
      ProposalFinalizedEvent.OutputObject
    >;

    "ResultPublished(uint256,uint32,uint32,string)": TypedContractEvent<
      ResultPublishedEvent.InputTuple,
      ResultPublishedEvent.OutputTuple,
      ResultPublishedEvent.OutputObject
    >;
    ResultPublished: TypedContractEvent<
      ResultPublishedEvent.InputTuple,
      ResultPublishedEvent.OutputTuple,
      ResultPublishedEvent.OutputObject
    >;

    "VoteCast(uint256,address)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
